import { FormInstance, Form } from 'antd'
import React from 'react'
import { PasswordItem } from '~/components/molecules/form-item/password'
import { getAutoGeneratePassword } from '~/modules/features/user/utils'
import { KeyOutlined } from '@ant-design/icons'

import Button from '~/components/atoms/button'

interface Props {
  form: FormInstance
}

export const PasswordWithAUtoGenerator: React.FC<Props> = ({ form }) => {
  const onClickGeneratePassword = () => {
    const autoGeneratedPassword = getAutoGeneratePassword()
    form.setFieldsValue({ password: autoGeneratedPassword })
  }
  return (
    <>
      <PasswordItem />
      <Form.Item>
        <Button
          text="パスワードを自動生成"
          color="blue"
          htmlType="button"
          icon={<KeyOutlined />}
          onClick={onClickGeneratePassword}
        />
      </Form.Item>
    </>
  )
}
